services:
  guardian-app:
    build: .
    container_name: guardian-app
    restart: always
    ports:
      - "3015:3000"
    environment:
      - NODE_ENV=production
    networks:
      - tea-network

networks:
  tea-network:
    external: true
