services:
  guardian-app:
    build: .
    container_name: guardian-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    ports:
      - "3015:3000"
    environment:
      - NODE_ENV=production
    networks:
      - tea-network

networks:
  tea-network:
    external: true
